[bar.default]
background_opacity = 0.5
capsule = true
center = [ "workspaces", "clock", "notifications" ]
end = [
    "tray",
    "clipboard",
    "caffeine",
    "wallpaper",
    "network",
    "bluetooth",
    "volume",
    "input_volume",
    "battery",
    "session",
    "control-center"
]
margin_edge = 12
margin_ends = 12
padding = 6
shadow = false
start = [ "group:g1", "active_window", "media" ]

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "cpu", "ram", "temp" ]
    opacity = 1.0
    padding = 6.0


[widget.clock]
anchor = true
format = "{:%d. %b %H:%M}"

[widget.workspaces]
focused_output_only = true

[widget.media]
hide_when_no_media = true

[widget.network]
show_label = false
vpn_status = "both"
