[backdrop]
enabled = true

[bar.default]
background_opacity = 0.5
capsule = true
center = [ "workspaces", "clock", "notifications" ]
end = [
    "tray",
    "clipboard",
    "caffeine",
    "wallpaper",
    "network",
    "bluetooth",
    "volume",
    "input_volume",
    "battery",
    "session",
    "control-center"
]
margin_edge = 10
margin_ends = 10
shadow = false
start = [ "group:g1", "active_window", "media" ]

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "cpu", "ram", "temp" ]
    opacity = 1.0
    padding = 6.0

[calendar]
enabled = true

    [calendar.account.personal_google]
    type = "google"

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "dark_mode"

[keybinds]
down = [ "Down", "Ctrl+n" ]
up = [ "Up", "Ctrl+p" ]

[location]
auto_locate = true

[nightlight]
enabled = true

[shell.panel]
transparency_mode = "glass"

[theme]
builtin = "Tokyo-Night"
mode = "dark"
source = "builtin"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "alacritty", "btop", "gtk3", "gtk4", "niri", "qt" ]

[wallpaper]
per_monitor_directories = true
transition_on_startup = true

    [wallpaper.automation]
    enabled = true

    [wallpaper.monitor.DP-2]
    directory = "/home/lukas/Pictures/Wallpapers/DP-2"

    [wallpaper.monitor.eDP-1]
    directory = "/home/lukas/Pictures/Wallpapers/eDP-1"

[widget.clock]
format = "{:%d. %b %H:%M}"

[widget.media]
hide_when_no_media = true

[widget.network]
show_label = false
vpn_status = "both"
